name: Build

on: [push, pull_request]

jobs:
  test:
    name: Plugin Testing
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
      # Install development dependencies
      - uses: jdx/mise-action@v2
      # Lint project files
      - run: ./scripts/lint.bash
      # Test plugin
      - run: ./scripts/test.bash
